
class PsValueHolder {
  PsValueHolder({
    required this.loginUserId,
    required this.userIdToVerify,
    required this.userNameToVerify,
    required this.userEmailToVerify,
    required this.userPasswordToVerify,
    required this.deviceToken,
    required this.notiSetting,
    required this.isToShowIntroSlider,
    required this.overAllTaxLabel,
    required this.overAllTaxValue,
    required this.shippingTaxLabel,
    required this.cityId,
    required this.messenger,
    required this.whatsApp,
    required this.phone,
    required this.shippingTaxValue,
    required this.appInfoVersionNo,
    required this.appInfoForceUpdate,
    required this.appInfoForceUpdateTitle,
    required this.appInfoForceUpdateMsg,
    required this.startDate,
    required this.endDate,
    required this.paypalEnabled,
    required this.stripeEnabled,
    required this.codEnabled,
    required this.bankEnabled,
    required this.publishKey,
    required this.shippingId,
    required this.standardShippingEnable,
    required this.zoneShippingEnable,
    required this.noShippingEnable,
    required this.locationId,
    required this.locactionName,
    required this.locationLat,
    required this.locationLng,
  });
  String? loginUserId;
  String? userIdToVerify;
  String? userNameToVerify;
  String? userEmailToVerify;
  String? userPasswordToVerify;
  String? deviceToken;
  bool? notiSetting;
  bool isToShowIntroSlider;
  String? overAllTaxLabel;
  String? overAllTaxValue;
  String? shippingTaxLabel;
  String? cityId;
  String? messenger;
  String? whatsApp;
  String? phone;
  String? shippingTaxValue;
  String? appInfoVersionNo;
  bool? appInfoForceUpdate;
  String? appInfoForceUpdateTitle;
  String? appInfoForceUpdateMsg;
  String? startDate;
  String? endDate;
  String? paypalEnabled;
  String? stripeEnabled;
  String? codEnabled;
  String? bankEnabled;
  String? publishKey;
  String? shippingId;
  String? standardShippingEnable;
  String? zoneShippingEnable;
  String? noShippingEnable;
  String? locationId;
  String? locactionName;
  String? locationLat;
  String? locationLng;
}
