name: fluttercity
description: A new Flutter city application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0+13
publish_to: none
# CCV 1.9 = 1.9.1+11
# CCV 1.9 = 1.9.0+11
# CCV 1.8 = 1.8.0+9
# CCV 1.7 = 1.7.0+8
# CCV 1.6 = 1.6.0+7
# CCV 1.5 = 1.5.0+6
# CCV 1.4 = 1.4.0+5
# CCV 1.3 = 1.3.0+4
# CCV 1.2 = 1.2.0+3
# CCV 1.1 = 1.1.0+2
# CCV 1.0 = 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  "mailer": ^5.1.0
  shared_preferences: 2.0.18
  http: 0.13.5
  provider: 6.0.3
  connectivity: 3.0.6
  cached_network_image: 3.2.3
  theme_manager: 1.1.0
  flutter_map: ^4.0.0
  image_picker: ^0.8.6+4
#  reactive_multi_image_picker: 0.7.0
  easy_localization: 3.0.1
  latlong2: 0.8.1
  flutter_html: 2.2.1
  sembast: 3.4.0+6
  path_provider: 2.0.13
  intl: 0.17.0
  shimmer: 2.0.0
  url_launcher: 6.1.10
  carousel_slider: 4.2.1
  firebase_core: 1.20.1
  firebase_core_platform_interface: 4.5.1
  firebase_messaging: 11.0.0
  firebase_auth: 3.11.2
  # flutter_native_admob: 2.1.0+3
  firebase_database: 7.2.1
  google_sign_in: 6.0.1
  flutter_facebook_auth: 4.0.0
  flutter_speed_dial: 6.2.0
  dio: any
  photo_view: 0.14.0
  progress_dialog_null_safe: 1.0.7
  flutter_braintree:  3.0.0
  launch_review: 3.0.1
  package_info_plus: 1.4.3
  fluttericon: 2.0.0
  flutter_stripe: 4.0.0
  # path: packages/flutter_stripe
  # google_mobile_ads: 0.12.2+1
  google_mobile_ads : 2.3.0
  flutter_credit_card: 3.0.3
  fluttertoast: 8.2.1
  permission_handler: 10.2.0
  permission_handler_platform_interface: ^3.9.0
  # geocode: 1.0.2
  the_apple_sign_in: 1.1.1
  razorpay_flutter: 1.3.4
  group_radio_button: 1.3.0
  # flutter_paystack: 1.0.5+1
  flutter_native_image: 0.0.6+1
  in_app_purchase: 1.0.9
  share_plus: 6.3.1
  firebase_dynamic_links: 4.3.4
  google_maps_flutter: 2.1.12
  flutter_datetime_picker: 1.5.1
  firebase_crashlytics: 2.8.8
permission_handler: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_local_notifications:
  #  path: lib/utils/local_noti/
#  firebase_auth_platform_interface: 6.10.0
#  firebase_core_platform_interface: 4.5.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/langs/ar-DZ.json
    - assets/langs/en-US.json
    - assets/langs/hi-IN.json
    - assets/langs/de-DE.json
    - assets/langs/es-ES.json
    - assets/langs/fr-FR.json
    - assets/langs/id-ID.json
    - assets/langs/it-IT.json
    - assets/langs/ja-JP.json
    - assets/langs/ko-KR.json
    - assets/langs/ms-MY.json
    - assets/langs/pt-PT.json
    - assets/langs/ru-RU.json
    - assets/langs/th-TH.json
    - assets/langs/tr-TR.json
    - assets/langs/zh-CN.json
    - assets/langs/fa-IR.json
    - assets/images/verify_email_icon.jpg
    - assets/images/baseline_feature_circle_24.png
    - assets/images/baesline_access_time_black_24.png
    - assets/images/baseline_check_green_24.png
    - assets/images/baseline_check_green_25.png
    - assets/images/baseline_graph_black_24.png
    - assets/images/baseline_price_down_black_24.png
    - assets/images/baseline_price_up_black_24.png
    - assets/images/arm.png
    - assets/images/baseline_percent_tag_orange_24.png
    - assets/images/baseline_empty_item_grey_24.png
    - assets/images/baseline_promotion_color_74.png
    - assets/images/home_icon/discount_products.png
    - assets/images/home_icon/easy_payment.png
    - assets/images/home_icon/featured_products.png
    - assets/images/home_icon/free_download.png
    - assets/images/delivery_car_img.png
    - assets/images/trending.png
    - assets/images/seo.png
    - assets/images/contact.png
    - assets/images/rating.png
    - assets/images/user_default_photo.png
    - assets/images/demo_alert.png






  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Bold-Italic.ttf
        - asset: assets/fonts/Product-Sans-Bold.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
cupertino_icons: ^1.0.2
androidX: true